### ISSUE TITLE
Select multiple items without using shift or command key

### ISSUE THREAD

**Issue by iandelrio** [ubceats/foodfoodfood#17]
Clicking on multiple different tags should highlight all of them. Right now, clicking on one and then clicking on another unselects the first.

**Comment by agottardo** [comment]
Time to learn some jQuery! https://stackoverflow.com/questions/8641729/how-to-avoid-the-need-for-ctrl-click-in-a-multi-select-box-using-javascript

Also https://codepen.io/gmkhussain/pen/ozwwPw

**Comment by iandelrio** [comment]
So it's purely a front-end thing?

**Comment by agottardo** [comment]
Yes. Add that code to `filterfooditems.phtml`.

**Comment by agottardo** [comment]
Fixed in 2f01e8c1f09b21df98855ba958f1abe84037e414.
